/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package great;

import org.junit.Test;
import org.junit.BeforeClass;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

import static org.junit.Assert.*;

import java.time.Duration;

import org.junit.After;
import org.junit.Before;

public class GreatTest {
    public WebDriver driver;

    @BeforeClass
    public static void setDriver() {
        WebDriverManager.chromedriver().setup();
    }

    @Before
    public void setupDriver() {
        this.driver = new ChromeDriver();
        driver.get("https://testlink.org");
        driver.manage().window().maximize();
    }

    @After
    public void closeDriver() {
        this.driver.close();
    }

    @Test
    public void correctTitle() {
        implicityWaitMilliseconds(500);
        String title = driver.getTitle();
        assertEquals("TestLink", title);
    }

    @Test
    public void correctHeaderContents() {
        implicityWaitMilliseconds(500);
        WebElement navBarLogo = driver.findElement(By.className("text-muted"));
        String navBarLogoText = navBarLogo.getText();
        assertEquals("TestLink", navBarLogoText);

        implicityWaitMilliseconds(500);
        WebElement header = driver.findElement(By.cssSelector(".jumbotron > h1"));
        String headerText = header.getText();
        assertEquals("TestLink Open Source Test Management", headerText);
    }

    @Test
    public void githubLinkRedirectsToRightProfile() {
        navigateToGithub();

        String currentDriverUrl = driver.getCurrentUrl();
        String githubUrlUsername = currentDriverUrl.split("/")[3];
        assertEquals("TestLinkOpenSourceTRMS", githubUrlUsername);
        
        WebElement githubPageProfileAnchor = driver.findElement(By.cssSelector(".url.fn"));
        String githubProfile = githubPageProfileAnchor.getText();
        assertEquals("TestLinkOpenSourceTRMS", githubProfile);
    }

    @Test
    public void githubSearchReturnsSomeResults() {
        navigateToGithub();
        
        WebElement headerSearchInput = driver.findElement(By.className("header-search-input"));
        headerSearchInput.sendKeys("hello world");
        headerSearchInput.sendKeys(Keys.ENTER);
        implicityWaitMilliseconds(1500);

        WebElement searchResultsElement = driver.findElement(By.xpath("//h3[contains(text(), 'code results')]"));
        String searchResultsText = searchResultsElement.getText().split(" ")[0];
        Integer searchResultsAmount = Integer.parseInt(searchResultsText);
        assertTrue(searchResultsAmount > 0);
    }

    public void navigateToGithub() {
        WebElement githubLinkAnchor = driver.findElement(By.linkText("Access Git Repository (GitHub)"));
        githubLinkAnchor.click();
        implicityWaitMilliseconds(1500);
    }

    public void implicityWaitMilliseconds(long timeInMilliseconds) {
        driver.manage().timeouts().implicitlyWait(Duration.ofMillis(timeInMilliseconds));
    }
}
